[package]
name = "tao_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
tao_middle = { path = "../middle" }
hashbrown = "0.11"
im = "15.0"
rand = "0.8"

[dev-dependencies]
tao_syntax = { path = "../syntax" }
tao_analysis = { path = "../analysis" }
